  # apache configuration playbook.
- hosts: 'ec2-3-17-29-162.us-east-2.compute.amazonaws.com'
  tasks: 
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    
    - name: Start and enable httpd service
      service:
        name: httpd
        enabled: true
        state: started
        
    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          Enable SysAdmin Demo:
          Ansible Profiling with Callback Plugin
          Custom Web Page
